### ISSUE TITLE
RuntimeError: value cannot be converted to type float without overflow: (3.32193e-07,-1.07936e-07)

### ISSUE THREAD

**Issue by huajng** [chenjun2hao/DDRNet.pytorch#16]
how to solve this running error?

**Comment by huajng** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 324, in <module>
    main()
  File "tools/train.py", line 288, in main
    trainloader, optimizer, model, writer_dict)
  File "/nfs/home/huanghaiyang/data5/method2f/DDRNet.pytorch-main/tools/../lib/core/function.py", line 74, in train
    optimizer.step()
  File "/nfs/home/huanghaiyang/.conda/envs/52f/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/home/huanghaiyang/.conda/envs/52f/lib/python3.6/site-packages/torch/optim/sgd.py", line 112, in step
    p.add_(d_p, alpha=-group['lr'])
RuntimeError: value cannot be converted to type float without overflow: (3.32193e-07,-1.07936e-07)
Traceback (most recent call last):
  File "/nfs/home/huanghaiyang/.conda/envs/52f/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/nfs/home/huanghaiyang/.conda/envs/52f/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/nfs/home/huanghaiyang/.conda/envs/52f/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/nfs/home/huanghaiyang/.conda/envs/52f/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/nfs/home/huanghaiyang/.conda/envs/52f/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/ddrnet23_slim.yaml']' returned non-zero exit status 1.
